plugins {
  id 'java-library'
  id 'maven-publish'
  id 'signing'
}


description 'Method Logging Extension for Spring'
group 'de.sayayi.lib'
version '0.5.0-SNAPSHOT'


layout.buildDirectory = '.build'


ext {
  jetbrainsAnnotationsVersion = '[24.0,26.1)'
  junitVersion = '5.11.+'
  log4jVersion = '[2.17.1,3.0.0)'
  lombokVersion = '1.18.+'
  messageFormatVersion = '[0.8.0,)'
  slf4jVersion = '[2.0.0,2.1.0)'
  logbackVersion = '[1.3.0,1.4.0)'
  springFrameworkVersion = '[5.3.0,6.0.0)'
}


java {
  registerFeature('optional') {
    usingSourceSet sourceSets.main
  }

  toolchain {
    languageVersion = JavaLanguageVersion.of(11)
  }
}


compileTestJava {
  options.debugOptions.debugLevel = 'lines,vars,source'
  options.compilerArgs = [ '-parameters' ]
}


test {
  useJUnitPlatform()
}


repositories {
  maven {
    url 'https://oss.sonatype.org/content/repositories/snapshots/'
    mavenContent {
      includeGroup 'de.sayayi.lib'
      snapshotsOnly()
    }
  }

  mavenCentral()
}


dependencies {
  // java
  compileOnlyApi "org.jetbrains:annotations:${jetbrainsAnnotationsVersion}"

  optionalCompileOnlyApi "org.slf4j:slf4j-api:${slf4jVersion}"
  optionalCompileOnlyApi "org.apache.logging.log4j:log4j-api:${log4jVersion}"
  optionalCompileOnlyApi "ch.qos.logback:logback-classic:${logbackVersion}"

  implementation "org.springframework:spring-context:${springFrameworkVersion}"
  implementation "de.sayayi.lib:message-format:${messageFormatVersion}"


  // test
  testAnnotationProcessor "org.projectlombok:lombok:${lombokVersion}"

  testCompileOnly "org.jetbrains:annotations:${jetbrainsAnnotationsVersion}"
  testCompileOnly "org.projectlombok:lombok:${lombokVersion}"

  testImplementation "org.junit.jupiter:junit-jupiter-api:${junitVersion}"
  testImplementation "org.springframework:spring-test:${springFrameworkVersion}"

  testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:${junitVersion}"
  testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}


def resolvedJetbrainsAnnotationsVersion = configurations
    .compileClasspath
    .resolvedConfiguration
    .resolvedArtifacts
    .find { it.name == 'annotations' }
    .moduleVersion.id.version

def resolvedMessageFormatVersion = configurations
    .compileClasspath
    .resolvedConfiguration
    .resolvedArtifacts
    .find { it.name == 'message-format' }
    .moduleVersion.id.version

def resolvedSpringFrameworkVersion = configurations
    .compileClasspath
    .resolvedConfiguration
    .resolvedArtifacts
    .find { it.name == 'spring-context' }
    .moduleVersion.id.version


javadoc {
  title "Spring Method Logging Extension ${version}"

  (options as StandardJavadocDocletOptions).with {
    linksOffline "https://javadoc.io/doc/org.jetbrains/annotations/${resolvedJetbrainsAnnotationsVersion}/",
                 'gradle/javadocs/jetbrains-annotations'
    linksOffline "https://javadoc.io/doc/de.sayayi.lib/message-format/${resolvedMessageFormatVersion}/",
                 'gradle/javadocs/message-format'
    linksOffline "https://javadoc.io/doc/org.springframework/spring-beans/${resolvedSpringFrameworkVersion}/",
                 'gradle/javadocs/spring-beans'
    linksOffline "https://javadoc.io/doc/org.springframework/spring-context/${resolvedSpringFrameworkVersion}/",
                 'gradle/javadocs/spring-context'
    linksOffline "https://javadoc.io/doc/org.springframework/spring-core/${resolvedSpringFrameworkVersion}/",
                 'gradle/javadocs/spring-core'

    encoding 'UTF-8'

    group('Spring Method Logging', [
        'de.sayayi.lib.methodlogging',
        'de.sayayi.lib.methodlogging.annotation',
        'de.sayayi.lib.methodlogging.logger'
    ])

    noQualifiers 'java.util', 'java.lang'

    addStringOption('Xdoclint:-missing', '-quiet')
  }

  failOnError false

  exclude 'de/sayayi/lib/methodlogging/internal/**'
}


apply from: file('gradle/publishing.gradle')
